main:
	g++ main.cpp -std=c++17 -o main
	./main
prime:
	g++ -std=c++20 prime.cpp -o prime -ftemplate-depth=99999999
	./prime
n_dim:
	g++ -std=c++20 n_dim.cpp -o n_dim
	./n_dim
test-constexpr:
	g++ -std=c++17 test_constexpr.cpp -o test_constexpr
	./test_constexpr
